/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package gal.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int KEY = 5;
  /** RegularExpression Id. */
  int CONDITION = 6;
  /** RegularExpression Id. */
  int ACTION = 7;
  /** RegularExpression Id. */
  int SPECIAL_KEY = 8;
  /** RegularExpression Id. */
  int DIRECTION = 9;
  /** RegularExpression Id. */
  int CATEGORY = 10;
  /** RegularExpression Id. */
  int MOUSE = 11;
  /** RegularExpression Id. */
  int UNDERSCORE = 12;
  /** RegularExpression Id. */
  int CAPITAL = 13;
  /** RegularExpression Id. */
  int LOWERCASE = 14;
  /** RegularExpression Id. */
  int LETTER = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int DOLLAR = 17;
  /** RegularExpression Id. */
  int NOT = 18;
  /** RegularExpression Id. */
  int MINUS = 19;
  /** RegularExpression Id. */
  int OPP = 20;
  /** RegularExpression Id. */
  int CONJUNCTION = 21;
  /** RegularExpression Id. */
  int DISJUNCTION = 22;
  /** RegularExpression Id. */
  int SEQUENCE = 23;
  /** RegularExpression Id. */
  int IDENTIFIER = 24;
  /** RegularExpression Id. */
  int NAT = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"Key\"",
    "<CONDITION>",
    "<ACTION>",
    "<SPECIAL_KEY>",
    "<DIRECTION>",
    "<CATEGORY>",
    "<MOUSE>",
    "\"_\"",
    "<CAPITAL>",
    "<LOWERCASE>",
    "<LETTER>",
    "<DIGIT>",
    "\"$\"",
    "\"!\"",
    "\"-\"",
    "\"~\"",
    "\"&\"",
    "\"/\"",
    "\";\"",
    "<IDENTIFIER>",
    "<NAT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "\":\"",
    "\"|\"",
    "\"?\"",
    "\"%\"",
    "\",\"",
    "\".\"",
  };

}
